### ISSUE TITLE
first results overshoots

### ISSUE THREAD

**Issue by stephanschulz** [dzlonline/ofxBiquadFilter#1]
hi

thanks for this great addon.

i am using it to smooth out tracking points. when those points first appear the filter slings the point too much around. i mean it seems to think the last point was at 0,0, the next at the actual tracking position. as a result the filtered point is way past the actual point.

i thought maybe the first time i have this new tracking point i would just flood the filter with this new position, to avoid it considering 0,0.

but did not work.

any ideas on how i can init() it to my first point?

```
    posFilter.setFc(posFilter_fc);
    for(int i=0; i<100; i++){
        posFilter.update(curPos);
    }
```

**Comment by dzlonline** [comment]
Hi.

The filter has 'internal memory' and it is initialized to 0. Unfortunately
there is no way (unless you change the initialization in the init code) to
initialize to other than zero.
You may pass the initial value to the filter a number of times giving it
time to stabilize.

Hope it solves your problem.

Dzl

**Comment by stephanschulz** [comment]
thanks. for your advice.
